const mongoose=require('mongoose');
const UserSchema=new mongoose.Schema({
    username:{
        type:String,
        require:true,
        min:3,
        max:20
    },
    email:{
        type:String,
        require:true,
        unique:true
    },desc:{
        type:String,
        max:30
    },
    password:{
        type:String,
        require:true,
        min:3,
        max:6
    },
    profileImage:{
        type:String,
        default:''
    },
    coverImage:{
        type:String,
        default:''
    },
    city:{
        type:String,
       max:50
    },
  from:{
      type:String,
      max:50
  },
  relationship:{
      type:Number,
      enum:[1,2,3]
  },
    followers:{
        type:Array,
        default:[]
    },
    following:{
        type:Array,
        default:[]
    },
    
    isAdmin:{
        type:Boolean,
        default:false
    },
   
},{
    timestamps:true
})
module.exports=mongoose.model('User',UserSchema)